version: '3'

services:
  
  auth-db:
    image: postgres:11
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432

  auth-api:
    build: './auth-api'
    container_name: auth-api
    ports:
      - 8080:8080

  product-db:
    image: postgres:11
    container_name: product-db
    restart: always
    environment:
      - POSTGRES_DB=product-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5433:5432

  product-api:
    build: './product-api'
    container_name: product-api
    ports:
      - 8081:8081

  sales-db:
    image: mongo:latest
    container_name: sales-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017:27017
      - 28017:28017

  sales-api:
    build: './sales-api'
    container_name: sales-api
    ports:
      - 8082:8082

  sales_rabbit:
    image: rabbitmq:3-management
    container_name: sales_rabbit
    restart: always
    ports:
      - 5672:5672 
      - 25676:25676 
      - 15672:15672